# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(first_name: 'Amit', last_name: 'Singh', role: 'Developer')
User.create!(first_name: 'Anup', last_name: 'Kumar', role: 'Developer')
User.create!(first_name: 'Ajit', last_name: 'Devi', role: 'Developer')
User.create!(first_name: 'Brajesh', last_name: 'Kapoor', role: 'Developer')
User.create!(first_name: 'Bitu', last_name: 'Singh', role: 'Developer')
User.create!(first_name: 'Zuned', last_name: 'Sheak', role: 'Developer')
User.create!(first_name: 'Raihan', last_name: 'Singh', role: 'Developer')
User.create!(first_name: 'Anna', last_name: 'Marria', role: 'Developer')
User.create!(first_name: 'Rohit', last_name: 'Tiwari', role: 'Developer')

User.create!(first_name: 'Nitin', last_name: 'Singh', role: 'Project Manager')
User.create!(first_name: 'Roop', last_name: 'Kumar', role: 'Project Manager')
User.create!(first_name: 'Harjeet', last_name: 'Devi', role: 'Project Manager')
User.create!(first_name: 'Rino', last_name: 'Kapoor', role: 'Project Manager')
User.create!(first_name: 'Bran', last_name: 'Singh', role: 'Project Manager')
User.create!(first_name: 'Zunni', last_name: 'Sheak', role: 'Project Manager')
User.create!(first_name: 'Robert', last_name: 'Singh', role: 'Project Manager')
User.create!(first_name: 'Anupriya', last_name: 'Marria', role: 'Project Manager')
User.create!(first_name: 'Shubhankar', last_name: 'Tiwari', role: 'Project Manager')

User.create!(first_name: 'Deshmookh', last_name: 'Singh', role: 'Client')
User.create!(first_name: 'Skylar', last_name: 'Kumar', role: 'Client')
User.create!(first_name: 'Alex', last_name: 'Devi', role: 'Client')
User.create!(first_name: 'joi', last_name: 'Kapoor', role: 'Client')
User.create!(first_name: 'Matt', last_name: 'Singh', role: 'Client')
User.create!(first_name: 'Rooni', last_name: 'Sheak', role: 'Client')
User.create!(first_name: 'Priya', last_name: 'Singh', role: 'Client')
User.create!(first_name: 'Snehal', last_name: 'Marria', role: 'Client')
User.create!(first_name: 'Zinna', last_name: 'Tiwari', role: 'Client')

User.create!(first_name: 'Amit_1', last_name: 'Singh', role: 'Team Lead')
User.create!(first_name: 'Anup_1', last_name: 'Kumar', role: 'Team Lead')
User.create!(first_name: 'Ajit_1', last_name: 'Devi', role: 'Team Lead')
User.create!(first_name: 'Brajesh_1', last_name: 'Kapoor', role: 'Team Lead')
User.create!(first_name: 'Bitu_1', last_name: 'Singh', role: 'Team Lead')
User.create!(first_name: 'Zuned_1', last_name: 'Sheak', role: 'Team Lead')
User.create!(first_name: 'Raihan_1', last_name: 'Singh', role: 'Team Lead')
User.create!(first_name: 'Anna_1', last_name: 'Marria', role: 'Team Lead')
User.create!(first_name: 'Rohit_1', last_name: 'Tiwari', role: 'Team Lead')

User.create!(first_name: 'Roy', last_name: 'Singh', role: 'Owner')
User.create!(first_name: 'Zignesh', last_name: 'Kumar', role: 'Owner')
User.create!(first_name: 'Debu', last_name: 'Devi', role: 'Owner')
User.create!(first_name: 'Abhi', last_name: 'Kapoor', role: 'Owner')
User.create!(first_name: 'AJ', last_name: 'Singh', role: 'Owner')
User.create!(first_name: 'Nishi', last_name: 'Sheak', role: 'Owner')
User.create!(first_name: 'Deen', last_name: 'Singh', role: 'Owner')
